
INFO_FIRMWARE_NAME = 'develop'
INFO_HARDWARE_NAME = 'FRI3D2022'
INFO_HARDWARE_FOLDER = 'fri3d2022'
OTA_WEB_SERVER = 'hatchery.badge.team'
OTA_WEB_PORT = 433   
WOEZEL_WEB_SERVER = 'hatchery.badge.team'
INFO_HARDWARE_WOEZEL_NAME = 'fri3dcamp_2022'